# Generated by Django 4.2.26 on 2025-11-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='machine name, used to draw the menu', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order among siblings')),
                ('url', models.CharField(blank=True, help_text='Absolute or relative URL, e.g. /about/ or https://...', max_length=500)),
                ('named_url', models.CharField(blank=True, help_text='Django named URL (reverse name).', max_length=255)),
                ('named_url_kwargs', models.JSONField(blank=True, default=dict, help_text='JSON object for kwargs passed to reverse, e.g. {"pk": 3}', null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_app.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menuitem')),
            ],
            options={
                'ordering': ['menu', 'order', 'id'],
            },
        ),
    ]
